apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda-deprecation-webhook
  namespace: keda-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keda-deprecation-webhook
  namespace: keda-system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keda-deprecation-webhook
  namespace: keda-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keda-deprecation-webhook
subjects:
  - kind: ServiceAccount
    name: keda-deprecation-webhook
    namespace: keda-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keda-deprecation-webhook
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["keda.sh"]
    resources: ["scaledobjects", "scaledjobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keda-deprecation-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keda-deprecation-webhook
subjects:
  - kind: ServiceAccount
    name: keda-deprecation-webhook
    namespace: keda-system
