apiVersion: v1
kind: Service
metadata:
  name: keda-deprecation-webhook
  namespace: keda-system
  labels:
    app.kubernetes.io/name: keda-deprecation-webhook
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: /metrics
spec:
  selector:
    app.kubernetes.io/name: keda-deprecation-webhook
  ports:
    - name: webhook
      port: 443
      targetPort: 9443
      protocol: TCP
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
