apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-deprecated
  namespace: demo-deprecated
  labels:
    app: cpu-deprecated
spec:
  replicas: 1
  selector:
    matchLabels: { app: cpu-deprecated }
  template:
    metadata:
      labels: { app: cpu-deprecated }
    spec:
      containers:
        - name: app
          image: registry.k8s.io/pause:3.9
          resources:
            requests: { cpu: 50m, memory: 32Mi }
            limits:   { cpu: 200m, memory: 64Mi }
