apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-demo
  namespace: demo-prom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-demo
  template:
    metadata:
      labels:
        app: prom-demo
    spec:
      containers:
        - name: prom-demo
          image: registry.k8s.io/pause:3.9
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 32Mi
