apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kdw-selfsigned
  namespace: keda-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kdw-serving-cert
  namespace: keda-system
spec:
  secretName: kdw-tls
  duration: 8760h
  renewBefore: 720h
  dnsNames:
    - keda-deprecation-webhook.keda-system.svc
    - keda-deprecation-webhook.keda-system.svc.cluster.local
  issuerRef:
    name: kdw-selfsigned
    kind: Issuer
