apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keda-deprecation-webhook
  namespace: keda-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keda-deprecation-webhook
