apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-demo
  namespace: demo-cpu
spec:
  scaleTargetRef:
    name: cpu-demo
  pollingInterval: 15
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 6
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "50"
